# Configuration file for VDN RNN evaluation on Road environments
CHECKPOINT_PATH: Null  # Path to the checkpoint directory containing config.yaml and the checkpoints folder
STEP: Null  # The step number of the checkpoint to evaluate
VMAPPED_SEED: 0  # Which vmapped seed to use (if multiple were used during training)

# Test parameters
TEST_NUM_ENVS: 1000  # Number of parallel environments to use during evaluation
TEST_NUM_STEPS: 50  # Number of steps to run in each environment during evaluation

# Randomness control
SEED: 0  # Random seed for the evaluation

# hydra params
hydra:
  run:
    dir: ${CHECKPOINT_PATH}/eval/${now:%Y-%m-%d_%H-%M-%S.%f}  # Directory to save evaluation results