"NUM_UPDATES": 12000
"NUM_ENVS": 32
"NUM_STEPS": 51
"BUFFER_SIZE": 5000
"BUFFER_BATCH_SIZE": 64
"HIDDEN_SIZE": 512
"EPS_START": 1.0
"EPS_FINISH": 0.0
"EPS_DECAY": 0.1 # percentage of updates
"MAX_GRAD_NORM": 12.5
"TARGET_UPDATE_INTERVAL": 32
"TAU": 1
"NUM_EPOCHS": 4
"LR": 0.0005
"LEARNING_STARTS": 10000 # timesteps
"LR_LINEAR_DECAY": False
"GAMMA": 0.99
"MIXER_EMBEDDING_DIM": 64
"MIXER_HYPERNET_HIDDEN_DIM": 128
"MIXER_INIT_SCALE": 0.001

# ENV
"ENV_NAME": "road_env"
"ENV_KWARGS":
  "map_name": "Cologne-v1"
  "encoding_type": "none"      # can be binary, one-hot, sinusoidal or none
  "include_extra_observations": 
    "segment_lengths": True     # Length of the segments
    "volumes": True             # Volumes of the vehicles on the segment normalized by the segment capacity
    "capacity": False           # Capacity of the segments

"REW_SCALE": 1e-8

# evaluate
"TEST_DURING_TRAINING": True
"TEST_INTERVAL": 0.01 # as a fraction of updates
"TEST_NUM_STEPS": 51
"TEST_NUM_ENVS": 1000

"ALG_NAME": "qmix_rnn"

############ global params ############

# experiment params
"NUM_SEEDS": 1 # number of vmapped seeds
"SEED": Null

"HYP_TUNE": False # perform hyp tune

# wandb params
"ENTITY": "imp-act"
"PROJECT": "jaxMARL"
"WANDB_MODE": "online"
"WANDB_LOG_ALL_SEEDS": False # will log separately the vmapped seeds

# checkpointing
"SAVE_CHECKPOINTS": True # save checkpoints
"SAVE_CHECKPOINTS_INTERVAL": 0.01 # as a fraction of updates. Tipp: set to same value or fraction of TEST_INTERVAL.

# precision
"DOUBLE_PRECISION_MODE": False # use double precision for the environment

# hydra params
hydra:
  run:
    dir: outputs/${ENV_KWARGS.map_name}/${ALG_NAME}/${now:%Y-%m-%d_%H-%M-%S.%f}