command:
  - ${env}
  - python
  - ${program}
  - --config-path=./config/final_runs/cologne_v1
entity: imp-act
method: grid
metric:
  goal: maximize
  name: test_returned_episode_returns
name: vdn_rnn_final_run
parameters:
  SEED:
    values:
      - 1221700768
      - 3410157204
      - 1116695186
      - 2006757533
      - 1989696838
      - 3979383719
      - 1191826828
      - 1362152812
      - 1950933211
      - 3846780909

program: getting-started/vdn_rnn_road_env.py
project: jaxMARL-Cologne-v1-final