command:
  - ${env}
  - python
  - ${program}
  - --config-path=./config/hyper_parameter_tuning/cologne_bonn_dusseldorf_v1
entity: imp-act
method: random
metric:
  goal: maximize
  name: test_returned_episode_returns
name: pqn_rnn_hyperparameter_tuning
parameters:
  # --- General Hyperparameters ---
  NUM_UPDATES:
    value: 2000
  NUM_ENVS:
    values: [128, 256]
  NUM_STEPS:
    value: 51
  MEMORY_WINDOW:
    value: 4
  HIDDEN_SIZE:
    values: [64, 128]
  NUM_LAYERS:
    value: 2
  NORM_INPUT:
    value: True
  NORM_TYPE:
    value: "batch_norm"
  MAX_GRAD_NORM:
    value: 1
  NUM_MINIBATCHES:
    value: 16
  NUM_EPOCHS:
    value: 4
  LR:
    value: 0.0001 # 1e-4
  LR_LINEAR_DECAY:
    value: False
  GAMMA:
    value: 0.99
  LAMBDA:
    value: 0.85

  # --- Exploration ---
  EPS_START:
    value: 1
  EPS_FINISH:
    value: 0
  EPS_DECAY:
    value: 0.1

  # --- Environment/Reward ---
  REW_SCALE:
    value: 1.0e-9 # 1.00E-09

  # --- Environment Configuration ---
  ENV_KWARGS:
    value:
      encoding_type: none
      include_extra_observations:
        segment_lengths: true
        volumes: true
        capacity: false
      map_name: CologneBonnDusseldorf-v1

program: getting-started/pqn_vdn_rnn_road_env.py
project: jaxMARL-CologneBonnDusseldorf-v1
