map: ToyExample-v2  # Options: ToyExample-v2, Cologne-v1, CologneBonnDusseldorf-v1
policy: humble_heuristic  # Options: do_nothing, random, humble_heuristic
policy_params:
  inspection_interval: 6  # Every n timesteps the policy will perform inspection (action 1)
  repair_threshold: 1     # When observation exceeds this value, repair action is taken (action 2)
num_episodes: 10000
num_steps: 50
norm_constant: 1e6
plot_histogram: False
double_precision_mode: False
priorization_params: 
  priorization_key: "random" # Options: "segment_lengths", "costs", "volumes"
  priorization_sign: "positive"
  random_seed: 29 # Options: "random", integernumber

# Optimization parameters
optimization:
  chunk_size: 5
  interval_start: 1
  interval_end: 51
  threshold_start: 1
  threshold_end: 6