policy: do_nothing  # Options: do_nothing, random, humble_heuristic
policy_params:
  inspection_interval: 6  # Every n timesteps the policy will perform inspection (action 1)
  repair_threshold: 1     # When observation exceeds this value, repair action is taken (action 2)
num_episodes: 1000
num_steps: 50
norm_constant: 1e6
plot_histogram: True
double_precision_mode: False
"env_kwargs":
  "map_name": "ToyExample-v1"      # Options: ToyExample-v2, Cologne-v1, CologneBonnDusseldorf-v1
  "encoding_type": "none"       # can be binary, one-hot, sinusoidal or none
  "include_extra_observations": 
    "segment_lengths": True     # Length of the segments
    "volumes": True             # Volumes of the vehicles on the segment normalized by the segment capacity
    "capacity": False           # Capacity of the segments