map: CologneBonnDusseldorf-v1-unconstrained
policy: segment_based_heuristic
num_envs: 5000
num_steps: 100
norm_constant: 1e6
plot_histogram: False
double_precision_mode: False
policy_parameters:
  inspection_interval: 1
  repair_threshold: 2
  prioritization_enabled: False

# hydra params
hydra:
  run:
    dir: outputs/${map}/segment_based_heuristic/eval/${now:%Y-%m-%d_%H-%M-%S.%f}
