EVALUATION_PATH: "outputs/Cologne-v1/ippo_rnn"
TEST_NUM_ENVS : 10000
TEST_NUM_EPISODES: 10000
VMAPPED_SEED : 0
EVAL_SEED : 0
REWARD_SCALE : 1e6
BASE_PATH : Null
TOP_K_CHECKPOINTS : Null

hydra:
  run:
    dir: outputs/evaluation/${now:%Y-%m-%d_%H-%M-%S.%f}  # Directory to save evaluation logs